[template]
src = "start.sh.tmpl"
dest = "/usr/bin/start.sh"
mode = "0755"
keys = [       
         "/base/dir",
         "/ip/addr",
         "/horus/polymerizer/port",
         "/consul/port",
         "/consul/datacenter",
         "/horus/server/port",
         "/horus/polymerizer/db/user",
         "/horus/polymerizer/db/name",
         "/horus/polymerizer/db/port",
         "/horus/polymerizer/db/pwd",
         "/horus/polymerizer/db/host",
         "/cb1",
         "/cb2",
         "/cb3",
]
