[template]
src = "consul_template.sh.tmpl"
dest = "//HORUS-SERVER/scripts/consul_template/consul_template.sh"
owner = "root"
mode = "0777"
keys = [
         "/ip/addr",
         "/consul/port",
         "/cb1",
         "/cb2",
         "/cb3",
]

