[template]
src = "horus_template.sh.tmpl"
dest = "/scripts/horus_template/horus_template.sh"
keys = [
         "/ip/addr",
         "/horus/server/port",
         "/cb1",
         "/cb2",
         "/cb3",
]

