[template]
src = "horus_template.sh.tmpl"
dest = "/HORUS-SERVER/scripts/horus_template/horus_template.sh"
owner = "root"
mode = "0777"
keys = [
         "/ip/addr",
         "/horus/server/port",
         "/cb1",
         "/cb2",
         "/cb3",
]

