[template]
src = "consul.toml"
dest = "/CONSUL-AGENT/conf/consul.json"
owner = "root"
mode = "0644"
keys = [
   "/consul/datacenter",
   "/consul/serverlocal",
   "/consul/server1",
   "/consul/server2",
   "/consul/server3",
   "/consul/name",
]
